# Site settings
title: IBlog博客
subtitle: Stay Hungry,Stay Foolish
description: 求知若渴，虚心若愚
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: email@yourdomain.com

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: # true
google_search: true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about

# Related Posts
relates: # 相关推荐
  - title: GitHup
    url: https://github.com/henucg
  - title: 
    url: 
  - title: 
    url: 

# Link settings
links: # 友情链接
  - title: 
    url: 
  - title: 
    url: 
  - title: 
    url: 