# Site settings
title: IBlog博客
subtitle: Stay Hungry,Stay Foolish
author: CG
description: 求知若渴，虚心若愚
baseurl: "/iblog" # the subpath of your site, e.g. /iblog
url: "https://henucg.github.io/iblog/" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: henucg@126.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
plugins: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Slogan
sloganTitle: Slogan
sloganContent: 求知若渴，虚心若愚


# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about

# Related Posts
relates: # 相关推荐
  - title: GitHup
    url: https://github.com/henucg

# Link settings
links: # 友情链接
  - title: 
    url: 
  - title: 
    url: 
  - title: 
    url: 

# baidu setting 百度统计的ID，如果引用此模版，请修改为自己的ID
baiduId: dfbdfe06cc30f1cf5adb15008fa36c46